{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.liujingxing",
    "module": "XmlClassGuard",
    "version": "1.3.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.codehaus.groovy",
          "module": "groovy-xml",
          "version": {
            "requires": "3.0.13"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "XmlClassGuard-1.3.1.jar",
          "url": "XmlClassGuard-1.3.1.jar",
          "size": 106058,
          "sha512": "3c6c565b16b914476e471d56209a00e02a7c2cf38dca3ebd7d8451ae2ba068be1ad5f7104dc5102811c18e3418a9fac88cf49bcf79963e4cc87f43329f4bc5b2",
          "sha256": "09ce0aa39937e4d78e9abbbf7142b768a75fa30edd62dd8177ef5529d3c3b016",
          "sha1": "96f1c79991ac625090b94ab02b413ce525ae6136",
          "md5": "ea5ef58886cf01afde1fe7fbd52f00f0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.codehaus.groovy",
          "module": "groovy-xml",
          "version": {
            "requires": "3.0.13"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "XmlClassGuard-1.3.1.jar",
          "url": "XmlClassGuard-1.3.1.jar",
          "size": 106058,
          "sha512": "3c6c565b16b914476e471d56209a00e02a7c2cf38dca3ebd7d8451ae2ba068be1ad5f7104dc5102811c18e3418a9fac88cf49bcf79963e4cc87f43329f4bc5b2",
          "sha256": "09ce0aa39937e4d78e9abbbf7142b768a75fa30edd62dd8177ef5529d3c3b016",
          "sha1": "96f1c79991ac625090b94ab02b413ce525ae6136",
          "md5": "ea5ef58886cf01afde1fe7fbd52f00f0"
        }
      ]
    }
  ]
}
