{
  "formatVersion": "1.1",
  "component": {
    "group": "com.bytedance.android",
    "module": "aabresguard-plugin",
    "version": "0.1.12",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.bytedance.android",
          "module": "aabresguard-core",
          "version": {
            "requires": "0.1.12"
          },
          "excludes": [
            {
              "group": "com.android.tools.build",
              "module": "bundletool"
            },
            {
              "group": "com.google.guava",
              "module": "guava"
            },
            {
              "group": "com.android.tools.build",
              "module": "gradle"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "aabresguard-plugin-0.1.12.jar",
          "url": "aabresguard-plugin-0.1.12.jar",
          "size": 22541,
          "sha512": "a8632803a959f61e61fa15d86ff99ba161fe362eedf2d0238968133be831445d09317c8c3b4e0a1367647f0c0aa739e22538cf6953d32f60faf77a9ab1d0c16c",
          "sha256": "6f2b55e0a9916ef5895c379f7e769239255f964e597f47b4e8d0e8c0bac93a13",
          "sha1": "0cf38e99bd1c21e2960ee3ca79a765c69f5c6299",
          "md5": "11a97b05e55c5fed346af1026da25a59"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.8.0"
          },
          "excludes": [
            {
              "group": "com.android.tools.build",
              "module": "bundletool"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.8.0"
          },
          "excludes": [
            {
              "group": "com.android.tools.build",
              "module": "bundletool"
            }
          ]
        },
        {
          "group": "com.bytedance.android",
          "module": "aabresguard-core",
          "version": {
            "requires": "0.1.12"
          },
          "excludes": [
            {
              "group": "com.android.tools.build",
              "module": "bundletool"
            },
            {
              "group": "com.google.guava",
              "module": "guava"
            },
            {
              "group": "com.android.tools.build",
              "module": "gradle"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "aabresguard-plugin-0.1.12.jar",
          "url": "aabresguard-plugin-0.1.12.jar",
          "size": 22541,
          "sha512": "a8632803a959f61e61fa15d86ff99ba161fe362eedf2d0238968133be831445d09317c8c3b4e0a1367647f0c0aa739e22538cf6953d32f60faf77a9ab1d0c16c",
          "sha256": "6f2b55e0a9916ef5895c379f7e769239255f964e597f47b4e8d0e8c0bac93a13",
          "sha1": "0cf38e99bd1c21e2960ee3ca79a765c69f5c6299",
          "md5": "11a97b05e55c5fed346af1026da25a59"
        }
      ]
    }
  ]
}
